theme: jekyll-theme-slate
author:
  name: Ben Rogers
  url: https://github.com/BenRogersWPG
title: Goodreads Achievements Guide | Unlock Every Badge
description: The full list of Goodreads achievements! Learn how to unlock every badge, complete themed reading challenges, and earn monthly goals throughout 2026.
defaults:
  - scope:
      path: ""
    values:
      image: /Media/Misc/Social_Preview/github-achievements-social-preview.jpg
      height: 1024
      width: 1792